// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVLKijqB9S3n2xkGrDSn5mos1MT8WCfrM',
    appId: '1:220814183760:web:9bd4bff4af59831272f055',
    messagingSenderId: '220814183760',
    projectId: 'thielal',
    authDomain: 'thielal.firebaseapp.com',
    storageBucket: 'thielal.firebasestorage.app',
    measurementId: 'G-9ZP8TTDCHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBoaDO_quUfvtuFMQr-h3q2K8s8SOWqXI',
    appId: '1:220814183760:android:940efc521c049f2872f055',
    messagingSenderId: '220814183760',
    projectId: 'thielal',
    storageBucket: 'thielal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKOciT_lMXPKD260NnkW7m0oapWFTEek',
    appId: '1:220814183760:ios:4ab3e58b9c19a0d272f055',
    messagingSenderId: '220814183760',
    projectId: 'thielal',
    storageBucket: 'thielal.firebasestorage.app',
    iosBundleId: 'com.example.thielal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKOciT_lMXPKD260NnkW7m0oapWFTEek',
    appId: '1:220814183760:ios:4ab3e58b9c19a0d272f055',
    messagingSenderId: '220814183760',
    projectId: 'thielal',
    storageBucket: 'thielal.firebasestorage.app',
    iosBundleId: 'com.example.thielal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVLKijqB9S3n2xkGrDSn5mos1MT8WCfrM',
    appId: '1:220814183760:web:e1492adb2039d4b772f055',
    messagingSenderId: '220814183760',
    projectId: 'thielal',
    authDomain: 'thielal.firebaseapp.com',
    storageBucket: 'thielal.firebasestorage.app',
    measurementId: 'G-JK3GTGLN1G',
  );
}
